#!/bin/bash

set -euo pipefail

RAM="4G"

IMAGE="${1-}"
ARCH="${2-x86_64}"

if [ -z "${IMAGE}" ]; then
    echo "Usage: ${0} image_name <arch>"
    exit -1
fi

if [ ! -f "${IMAGE}" ]; then
    echo "File does not exist: ${IMAGE}"
    exit -1
fi

echo "Using image: ${IMAGE}"

kvm-ok > /dev/null
if [ ! $? -eq 0 ]; then
    echo "Virtualisation is unavailable!"
    exit -1
fi

CMD="qemu-system-${ARCH} \
-enable-kvm \
-bios /usr/share/ovmf/OVMF.fd \
-drive format=raw,file=${IMAGE} \
-m "${RAM}" \
-cpu host \
-smp $(nproc) \
-vga virtio \
-device virtio-net,netdev=vmnic \
-netdev user,id=vmnic,hostfwd=tcp:127.0.0.1:2222-:22 \
"

echo "Running command: ${CMD}"
echo "Press ctrl+c or close the QEMU window to stop the virtualisation"
exec ${CMD}
